name: Daily Project Generator

on:
  workflow_dispatch:

jobs:
  generate-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug files
        run: |
          pwd
          ls -R

      - name: Run Script
        run: python generate_project.py

      - name: Commit & Push
        run: |
          git config --global user.name "Manisha Kanojia"
          git config --global user.email "manishakanojia95@gmail.com"
          git add .
          git commit -m "Auto daily project" || echo "No changes"
          git push
